### ISSUE TITLE
About your username

### ISSUE THREAD

**Issue by kazzkiq** [sevn/portfolio#1]
Hello @sevn, my name is Claudio Holanda and I would like to get in touch with you about your username in GitHub.

Do you have any email address that I can get in touch to? Or perhaps a Twitter account so I can DM you there?

Best Regards.

**Comment by anystar** [comment]
My personal email is darklocker@gmail.com. I'm open to discuss it :)

**Comment by kazzkiq** [comment]
Thanks! I'll get in touch. :-)
